pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'Building...'
            }
        }
        stage('Test') {
            steps {
                sh label: '', script: 'python jenkins/a2.py'
            }
        }
        stage('Deploy') {
            steps {
                sh label: '', script: 'python code/a1.py'
            }
        }
    }
}
