pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'Building...'
            }
        }
        stage('Test') {
            steps {
                sh label: '', script: 'python jenkins/a2.py'
            }
        }
        stage('Deploy') {
            steps {
                sh label: '', script: 'python code/a1.py'
            }
            post {
                always {
                    emailext body: 'success', subject: 'project testjks tested', to: 'lvgui@chipltech.com'
                }
            }
        }
    }
}
